### ISSUE TITLE
Exception wirh exists collection

### ISSUE THREAD

**Issue by Deichor** [Romitou/MongoSK#71] opened 2022-08-22 12:25 UTC
### 🔖 Versions

![image](https://user-images.githubusercontent.com/43517719/185920548-518b0f91-96a1-4add-96ca-197634c9cd3a.png)

### ✒️ Description

When creating a collection, it sends an exception if the collection exists.

### ⚙️ Expected behavior

It doesn't throw an exception or an error.

### 🔎 Steps to reproduce

I tried to create an existing collection.

### 📸 Errors or screenshots

`[15:07:10 INFO]: [org.mongodb.driver.connection] Opened connection [connectionId{localValue:15, serverValue:1558}] to localhost:27017
[15:07:10 ERROR]: [org.mongodb.driver.connection] Callback onResult call produced an error
java.lang.IllegalStateException: Attempted to decrement the reference count below 0
        at fr.romitou.mongosk.libs.driver.internal.connection.AbstractReferenceCounted.release(AbstractReferenceCounted.java:42) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.DefaultServerConnection.release(DefaultServerConnection.java:64) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.DefaultServer$AsyncOperationCountTrackingConnection.release(DefaultServer.java:406) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.operation.OperationHelper$ReferenceCountedReleasingWrappedCallback.onResult(OperationHelper.java:519) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.operation.CreateCollectionOperation$ProcessCommandsCallback.onResult(CreateCollectionOperation.java:558) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.operation.CreateCollectionOperation$ProcessCommandsCallback.onResult(CreateCollectionOperation.java:537) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.operation.CommandOperationHelper.lambda$addingRetryableLabelCallback$22(CommandOperationHelper.java:492) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.operation.CommandOperationHelper.lambda$transformingWriteCallback$11(CommandOperationHelper.java:340) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.DefaultServer$DefaultServerProtocolExecutor$2.onResult(DefaultServer.java:272) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.CommandProtocolImpl$1.onResult(CommandProtocolImpl.java:82) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.DefaultConnectionPool$PooledConnection$1.onResult(DefaultConnectionPool.java:683) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.UsageTrackingInternalConnection$2.onResult(UsageTrackingInternalConnection.java:159) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:523) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:498) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:821) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:785) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:645) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:642) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233) ~[MongoSK-2.3.0-all.jar:?]
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[?:?]
        at sun.nio.ch.Invoker.invokeDirect(Invoker.java:160) ~[?:?]
        at sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(UnixAsynchronousSocketChannelImpl.java:573) ~[?:?]
        at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:277) ~[?:?]
        at sun.nio.ch.AsynchronousSocketChannelImpl.read(AsynchronousSocketChannelImpl.java:298) ~[?:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:144) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:118) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:107) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:642) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection.access$600(InternalStreamConnection.java:86) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:775) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:760) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:645) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:642) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:250) ~[MongoSK-2.3.0-all.jar:?]
        at fr.romitou.mongosk.libs.driver.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:233) ~[MongoSK-2.3.0-all.jar:?]
        at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[?:?]`

**Comment by Romitou** [comment] 2022-08-22 21:30
Hello! 👋

Thank you for your bug report. After investigation, this error is caused by the Mongo driver that the addon is using. Therefore, I have opened an issue at [JIRA-4711](https://jira.mongodb.org/projects/JAVA/issues/JAVA-4711). Please be patient until the bug is solved on their side, I will keep you informed when MongoSK will be updated accordingly.

I also would like to point out that it would be useful when you report bugs to specify that you are using a custom build or a build from GitHub that has not been officially released yet, this will make it easier for the developers!

Have a nice day! 😀

**Comment by Romitou** [comment] 2022-11-04 15:33
Fixed in [2.3.1](https://github.com/Romitou/MongoSK/releases/tag/2.3.1). Thank you for reporting this bug. 🙂

**Closed by Romitou** 2022-11-04 15:33 UTC
Labels: bug, library issue
